http://localhost:8080
GET /api/users/

http://localhost:8080
GET /api/users/?expand=yes

http://localhost:8080
POST /api/users/
{
  "email": "mborkowski@test.com",
  "firstName": "Michał",
  "lastName": "Borkowski",
  "password": "psst",
  "role": "STUDENT"
}

http://localhost:8080
GET /api/users/4

http://localhost:8080
GET /api/activities/

http://localhost:8080
POST /api/activities/
{
  "name": "zajęcia dodatkowe",
  "startDate": 1507588400000
}

# doesn't work
http://localhost:8080
GET /api/activities/4

http://localhost:8080
POST /api/users/4/activities/
{
  "activityId": 2,
  "present": true
}

http://localhost:8080
PUT /api/users/4/activities/2
{
  "present": false
}
